apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-recommended-offer-list
spec:
  replicas: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: get-recommended-offer-list
  template:
    metadata:
      labels:
        app: get-recommended-offer-list
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: get-recommended-offer-list
        ports:
        - containerPort: 80
